// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

import "./globals.css";
import NavBar from "@/components/NavBar";
import SearchBar from "@/components/SearchBar";
import DataGrid from "@/components/DataGrid";

function Layout({children}) {
  
  return (
    <html lang="en">
    <body>
    
      <NavBar />
      <br />
      
      {children}
    </body>
    </html>
  );
}

export default Layout;
